Plant Paradise/Plant_Paradise/Plant_Paradise/Controllers/OrdersAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Plant_Paradise.Models;

namespace Plant_Paradise.Controllers
{
    public class OrdersAdminController : Controller
    {
        private PlantsEntities db = new PlantsEntities();

        // GET: OrdersAdmin
        public ActionResult Index()
        {
            var orders = db.Orders.Include(o => o.AspNetUser);
            return View(orders.ToList());
        }
        [HttpPost]
        public ActionResult search(string Search,int order=0)
        {
            var orders=db.Orders.Include(o => o.AspNetUser);    
            if(order==0 || order == 2)
            {
                orders= orders.Where(p=>p.AspNetUser.Full_Name.Contains(Search) || p.Order_id.Contains(Search));
            }
            else if (order == 1)
            {
                orders = orders.Where(p => (p.AspNetUser.Full_Name.Contains(Search) || p.Order_id.Contains(Search))&& p.Order_date==DateTime.Today);

            }

            return View("Index",orders.ToList());
        }
        // GET: OrdersAdmin/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: OrdersAdmin/Create
        public ActionResult Create()
        {
            ViewBag.userId = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

        // POST: OrdersAdmin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Order_id,Order_date,userId,Total_price")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.userId = new SelectList(db.AspNetUsers, "Id", "Email", order.userId);
            return View(order);
        }

        // GET: OrdersAdmin/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.userId = new SelectList(db.AspNetUsers, "Id", "Email", order.userId);
            return View(order);
        }

        // POST: OrdersAdmin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Order_id,Order_date,userId,Total_price")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.userId = new SelectList(db.AspNetUsers, "Id", "Email", order.userId);
            return View(order);
        }

        // GET: OrdersAdmin/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: OrdersAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Plant Paradise/Plant_Paradise/Plant_Paradise/Views/OrdersAdmin/Create.cshtml
@model Plant_Paradise.Models.Order

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLAyout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Order_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Order_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Order_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Order_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userId, "userId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("userId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.userId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total_price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total_price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Plant Paradise/Plant_Paradise/Plant_Paradise/Views/OrdersAdmin/Delete.cshtml
@model Plant_Paradise.Models.Order

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminLAyout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Order_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total_price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total_price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Plant Paradise/Plant_Paradise/Plant_Paradise/Views/OrdersAdmin/Details.cshtml
@model Plant_Paradise.Models.Order

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/AdminLAyout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Order_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total_price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total_price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Order_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Plant Paradise/Plant_Paradise/Plant_Paradise/Views/OrdersAdmin/Edit.cshtml
@model Plant_Paradise.Models.Order

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLAyout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Order_id)

        <div class="form-group">
            @Html.LabelFor(model => model.Order_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Order_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userId, "userId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("userId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.userId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total_price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total_price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Plant Paradise/Plant_Paradise/Plant_Paradise/Views/OrdersAdmin/Index.cshtml
@model IEnumerable<Plant_Paradise.Models.Order>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLAyout.cshtml";
}

<div class="page-header">
    <h1>Orders</h1>
    <small>Home / Orders</small>
</div>

<div class="page-content">

    <div class="records table-responsive">
        @using (Html.BeginForm("search", "OrdersAdmin"))
        {
        <div class="record-header">
            <div>
                <input type="radio" name="order" value="1">
                <label>Day Orders</label>

                <input type="radio" name="order" value="2">
                <label>All Orders</label>
            </div>
            <div class="add">

                <!-- <span>Entries</span>
                <select name="" id="">
                    <option value="">ID</option>
                </select> -->
            </div>

            <div class="">
                <input type="search" placeholder="Search" name="Search" style="margin:0;height: 33px !important;">
                <input type="submit" width="10px" style="margin:0;" value="search" class="btn btn-info">
            </div>
        </div>
        }
        <div>
            <table width="100%">

                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Order_id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Order_date)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Total_price)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.AspNetUser.Full_Name)
                        </th>
                        <th>Products</th>
                    </tr>
                <thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Order_id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Order_date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Total_price) JD
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AspNetUser.Full_Name)
                            </td>
                            <td>
                                
                               <a class="btn btn-success" href="/ViewProductFromAdmin/Index/@item.Order_id">View Products</a>
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>

    </div>
</div>