Plant Paradise/Plant_Paradise/Plant_Paradise/Controllers/CategoriesAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Plant_Paradise.Models;

namespace Plant_Paradise.Controllers
{
    public class CategoriesAdminController : Controller
    {
        private PlantsEntities db = new PlantsEntities();

        // GET: CategoriesAdmin
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }
        [HttpPost]
        public ActionResult search(string search)
        {
            var Categories=db.Categories.Where(p=>p.Category_Name.Contains(search)).ToList();  
            return View("Index", Categories.ToList());
        }

        public ActionResult Statistics()
        {
            return View();
        }
        // GET: CategoriesAdmin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: CategoriesAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoriesAdmin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Category_id,Category_Name,Category_Image")] Category category, HttpPostedFileBase Category_Image)
        {
            string fileName = fileName = Path.GetFileName(Category_Image.FileName);

            if (ModelState.IsValid)
            {
                string path = "/Images/" + Path.GetFileName(Category_Image.FileName);
                string path2 = Path.GetFileName(Category_Image.FileName);
                category.Category_Image = path2.ToString();
                Category_Image.SaveAs(Server.MapPath(path));


                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: CategoriesAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: CategoriesAdmin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id,[Bind(Include = "Category_id,Category_Name,Category_Image")] Category category, HttpPostedFileBase Category_Image)
        {
            if (ModelState.IsValid)
            {
                var existingModel = db.Categories.AsNoTracking().FirstOrDefault(x => x.Category_id == id);

                if (category != null)
                {
                    string path = "/Images/" + Path.GetFileName(Category_Image.FileName);
                    string path2 = Path.GetFileName(Category_Image.FileName);
                    Category_Image.SaveAs(Server.MapPath(path));
                    category.Category_Image = path2;
                }
                else
                {
                    category.Category_Image = existingModel.Category_Image;
                }

                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: CategoriesAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: CategoriesAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Plant Paradise/Plant_Paradise/Plant_Paradise/Views/CategoriesAdmin/Create.cshtml
@model Plant_Paradise.Models.Category

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLAyout.cshtml";
}


<br />
<br />
<br />
@using (Html.BeginForm("Create", "CategoriesAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="edit-product-form">
        <h2>Add Category</h2>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.LabelFor(model => model.Category_Name, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.EditorFor(model => model.Category_Name, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Category_Name, "", new { @class = "text-danger" })


        @Html.LabelFor(model => model.Category_Image, htmlAttributes: new { @class = "control-label col-md-2" })
        <input class="form-control text-box single-line" id="Category_Image" name="Category_Image" type="file" value="" />
        @Html.ValidationMessageFor(model => model.Category_Image, "", new { @class = "text-danger" })

        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}

Plant Paradise/Plant_Paradise/Plant_Paradise/Views/CategoriesAdmin/Delete.cshtml
@model Plant_Paradise.Models.Category

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminLAyout.cshtml";
}


<br /><br />
<div>
    <p style="width:47%;margin-left:auto;margin-right:auto;font-size:1.5rem;">
        Delete

    </p>
    <p style="width:47%;margin-left:auto;margin-right:auto;font-size:1.75rem;">
        Are you sure you want to delete this?

    </p>
</div>



<div class="container-fluid d-flex align-items-center flex-column">
    <div class="product-details">

        <label for="product-category">
            @Html.DisplayNameFor(model => model.Category_Name)
        </label>
        <span id="product-category">
            @Html.DisplayFor(model => model.Category_Name)
        </span>
        <label for="product-category">
            @Html.DisplayNameFor(model => model.Category_Image)

        </label>
        <span id="product-category">
            <img src="~/Images/@Model.Category_Image" class="img-circle img" />

        </span>
        </div></div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div style="display:flex;width:50%; margin-left:auto;margin-right:auto;">

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-danger" /> 
                    @Html.ActionLink("Back to List", "Index", null, new {@class="btn btn-primary"})
                </div>
                </div>
                }
          

Plant Paradise/Plant_Paradise/Plant_Paradise/Views/CategoriesAdmin/Details.cshtml
@model Plant_Paradise.Models.Category

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/AdminLAyout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category_Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category_Image)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Category_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Plant Paradise/Plant_Paradise/Plant_Paradise/Views/CategoriesAdmin/Edit.cshtml
@model Plant_Paradise.Models.Category

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLAyout.cshtml";
}

<br />
<br />
<br />
@using (Html.BeginForm("Edit", "CategoriesAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="edit-product-form">
        <h2>Edit Category</h2>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Category_id)


        @Html.LabelFor(model => model.Category_Name, htmlAttributes: new { @class = "control-label col-md-2" })

        @Html.EditorFor(model => model.Category_Name, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Category_Name, "", new { @class = "text-danger" })


        @Html.LabelFor(model => model.Category_Image, htmlAttributes: new { @class = "control-label col-md-2" })
        <input class="form-control text-box single-line" id="Category_Image" name="Category_Image" type="file" value="@Model.Category_Image" />
        @Html.ValidationMessageFor(model => model.Category_Image, "", new { @class = "text-danger" })
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })

            </div>
        </div>
    </div>
}

Plant Paradise/Plant_Paradise/Plant_Paradise/Views/CategoriesAdmin/Index.cshtml
@model IEnumerable<Plant_Paradise.Models.Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLAyout.cshtml";
}


<div class="page-header">
    <h1>Categories</h1>
    <small>Home / Categories</small>
</div>

<div class="page-content">

    <div class="records table-responsive">
        @using (Html.BeginForm("search", "CategoriesAdmin"))
        {
            <div class="record-header">
                <div class="add">
                    @Html.ActionLink("ِAdd Category", "Create", null, new { @class = "btn btn-primary" })
                </div>

                <div class="">
                    <input type="search" placeholder="Search" name="search" style="margin:0;height: 33px !important;">
                    <input type="submit" style="margin:0;" value="search" class="btn btn-info">
                </div>
            </div>
        }
        <div>
            <table width="100%">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Category_Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Category_Image)
                        </th>
                        <th>
                            Subcategories
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Category_Name)
                            </td>
                            <td>
                                <img src="~/Images/@item.Category_Image" class="img" />
                            </td>
                            <td>
                                <a class="btn btn-info" href="/Sub_CategoriesAdmin/Index/@item.Category_id">View Subcategories</a>
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.Category_id }, new { @class = "btn btn-success" })
                                @Html.ActionLink("Delete", "Delete", new { id = item.Category_id }, new { @class = "btn btn-danger" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>
</div>

Plant Paradise/Plant_Paradise/Plant_Paradise/Views/CategoriesAdmin/Statistics.cshtml
@{
    ViewBag.Title = "Statistics";
    Layout = "~/Views/Shared/AdminLAyout.cshtml";
}


<div class="page-header">
    <h1>Dashboard</h1>
    <small>Home / Dashboard</small>
</div>

<div class="page-content">

    <div class="analytics">

        <div class="card">
            <div class="card-head">
                <h2>107</h2>
                <span class="las la-user-friends"></span>
            </div>
            <div class="card-progress">
                <small>Users</small>


            </div>
        </div>

        <div class="card">
            <div class="card-head">
                <h2>230</h2>
                <span class="las la-comment"></span>
            </div>
            <div class="card-progress">
                <small>feedbacks</small>

            </div>
        </div>

        <div class="card">
            <div class="card-head">
                <h2>34</h2>
                <span class="las la-user-astronaut">


                </span>
            </div>
            <div class="card-progress">
                <small>Number of Products</small>

            </div>
        </div>

        <div class="card">
            <div class="card-head">
                <h2>500JD</h2>
                <span class="las la-dollar-sign">

                </span>
            </div>
            <div class="card-progress">
                <small>Total Revenues</small>

            </div>
        </div>



    </div>



</div>



<div class="page-content">

    <div class="analytics">

        <div class="card">
            <div class="card-head">
                <h2>107</h2>
                <span class="las la-user-friends"></span>
            </div>
            <div class="card-progress">
                <small>Users</small>


            </div>
        </div>

        <div class="card">
            <div class="card-head">
                <h2>230</h2>
                <span class="las la-comment"></span>
            </div>
            <div class="card-progress">
                <small>feedbacks</small>

            </div>
        </div>

        <div class="card">
            <div class="card-head">
                <h2>34</h2>
                <span class="las la-user-astronaut">


                </span>
            </div>
            <div class="card-progress">
                <small>Number of Products</small>

            </div>
        </div>

        <div class="card">
            <div class="card-head">
                <h2>500JD</h2>
                <span class="las la-dollar-sign">

                </span>
            </div>
            <div class="card-progress">
                <small>Total Revenues</small>

            </div>
        </div>



    </div>



</div>